import React from 'react'

// Simple AI Advisor: if VITE_OPENAI_KEY is provided, it will call OpenAI's chat completion endpoint.
// Otherwise it falls back to a small rule-based responder that gives gentle Islamic advice.

function fallbackAdvice(prompt){
  // very small rule-based responses to keep offline and safe
  const p = (prompt||'').toLowerCase()
  if(p.includes('sad') || p.includes('depressed') || p.includes('down')){
    return 'Remember that sadness is part of the human condition — take a moment to make dua, seek support from family, and consider small acts of worship like dhikr to soften the heart.'
  }
  if(p.includes('angry') || p.includes('frustrat')){
    return 'When anger rises, try stepping away, perform ablution if possible, and recite a short dua for patience. The Prophet ﷺ recommended seeking refuge in Allah and delaying action until calm.'
  }
  if(p.includes('grat')){
    return 'Gratitude is a powerful ibadah. Consider writing three specific blessings you felt today and say Alhamdulillah for each — it helps the heart remember.'
  }
  return 'Reflect on the short du`a: "Rabbi zidni ilma" — ask Allah for beneficial knowledge and steadfastness. If you want tailored advice, provide a short context and I will respond kindly.'
}

export default function AiAdvisor({prompt, autoAsk=false, hideInput=false}){
  const [loading, setLoading] = React.useState(false)
  const [reply, setReply] = React.useState('')

  async function ask(){
    const trimmed = (prompt||'').trim()
    if(!trimmed){
      setReply('Ask a short question about how to respond spiritually and I will try to help.')
      return
    }
    // For privacy and offline use we only use the local rule-based fallback here.
    setReply(fallbackAdvice(trimmed))
  }

  React.useEffect(()=>{
    if(autoAsk){
      ask()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [autoAsk, prompt])

  return (
    <div style={{marginTop:18, padding:12, borderRadius:12, border:'1px dashed rgba(17,75,43,0.06)', background:'linear-gradient(180deg,#fbfff9,#f7fffb)'}}>
      <div style={{fontWeight:700, color:'#114B2B', marginBottom:8}}>AI Spiritual Advisor</div>
      <div style={{color:'#3f6b58', marginBottom:10, fontSize:13}}>Get gentle Islamic advice generated by a local fallback or an optional AI key (set VITE_OPENAI_KEY).</div>
      {!hideInput && (
        <div style={{display:'flex', gap:8}}>
          <input value={prompt||''} readOnly placeholder="Your prompt will be taken from your entry" style={{flex:1, padding:10, borderRadius:8, border:'1px solid rgba(2,6,23,0.04)'}} />
          <button onClick={ask} style={{padding:'8px 12px', borderRadius:8, background:'linear-gradient(90deg,#06b6d4,#0891b2)', color:'#fff', border:'none'}}>{loading? 'Thinking...':'Ask'}</button>
        </div>
      )}
      {reply && <div style={{marginTop:12, padding:10, borderRadius:8, background:'#fff', boxShadow:'0 6px 18px rgba(2,6,23,0.04)'}}>{reply}</div>}
    </div>
  )
}
