name: Disabled - Firebase deploy removed

on: [workflow_dispatch]

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Firebase deploy workflow has been removed from this repository."
