name: Post-deploy smoke test

on:
  workflow_run:
    workflows: ["Deploy to Firebase Hosting"]
    types:
      - completed

jobs:
  post_deploy_smoke:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Ensure HOSTING_URL secret is set
        run: |
          if [ -z "$HOSTING_URL" ]; then echo "HOSTING_URL secret is missing — set it in repository secrets to enable post-deploy smoke tests"; exit 1; fi
        env:
          HOSTING_URL: ${{ secrets.HOSTING_URL }}

      - name: Ensure PROXY_TOKEN secret is set (if you enabled proxy token)
        run: |
          echo "If your proxy requires a token, ensure PROXY_TOKEN is set as a repo secret."
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install
        run: npm ci

      - name: Run smoke test against hosted site
        env:
          SMOKE_PROXY_URL: ${{ secrets.HOSTING_URL }}/api/proxyGemini
          SMOKE_PROXY_TOKEN: ${{ secrets.PROXY_TOKEN }}
        run: |
          node scripts/smoke_test_proxy.js "$SMOKE_PROXY_URL" "$SMOKE_PROXY_TOKEN"
