name: Post-deploy smoke test

on:
  workflow_run:
    workflows: ["Deploy to Firebase Hosting"]
    types:
      - completed

jobs:
  post_deploy_smoke:
    if: ${{ github.event.workflow_run.conclusion == 'success' && secrets.HOSTING_URL }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install
        run: npm ci

      - name: Run smoke test against hosted site
        env:
          SMOKE_PROXY_URL: ${{ secrets.HOSTING_URL }}/api/proxyGemini
          SMOKE_PROXY_TOKEN: ${{ secrets.PROXY_TOKEN }}
        run: |
          node scripts/smoke_test_proxy.js "$SMOKE_PROXY_URL" "$SMOKE_PROXY_TOKEN"
